// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using server.Models;

namespace server.Migrations
{
    [DbContext(typeof(CatsDbContext))]
    [Migration("20210317224819_CatModels")]
    partial class CatModels
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("server.Models.Cats.Cat", b =>
                {
                    b.Property<string>("CatId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<int>("Breed")
                        .HasColumnType("int");

                    b.Property<int>("BreedId")
                        .HasColumnType("int");

                    b.Property<int>("Color")
                        .HasColumnType("int");

                    b.Property<int>("ColorId")
                        .HasColumnType("int");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FatherId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<int>("GenderId")
                        .HasColumnType("int");

                    b.Property<string>("MotherId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfileImage")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CatId");

                    b.HasIndex("FatherId");

                    b.HasIndex("MotherId");

                    b.ToTable("Cats");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Cat");
                });

            modelBuilder.Entity("server.Models.Cats.Female", b =>
                {
                    b.HasBaseType("server.Models.Cats.Cat");

                    b.HasDiscriminator().HasValue("Female");
                });

            modelBuilder.Entity("server.Models.Cats.Male", b =>
                {
                    b.HasBaseType("server.Models.Cats.Cat");

                    b.HasDiscriminator().HasValue("Male");
                });

            modelBuilder.Entity("server.Models.Cats.Cat", b =>
                {
                    b.HasOne("server.Models.Cats.Male", "Father")
                        .WithMany("Children")
                        .HasForeignKey("FatherId");

                    b.HasOne("server.Models.Cats.Female", "Mother")
                        .WithMany("Children")
                        .HasForeignKey("MotherId");

                    b.Navigation("Father");

                    b.Navigation("Mother");
                });

            modelBuilder.Entity("server.Models.Cats.Female", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("server.Models.Cats.Male", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
